import type { Metadata } from "next";
import { Arsenal, Hedvig_Letters_Serif } from "next/font/google";
import "./page.scss";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme/theme";
import { Box, GlobalStyles } from "@mui/material";
import { globalStyling } from "@/theme/helpers/getGlobalStyling";


const fontRegular = Hedvig_Letters_Serif({
  variable: "--font-hedvig-letters-serif",
  subsets: ["latin"],
  weight: ["400"]
});
const fontBold = Arsenal({
  variable: "--font-arsenal",
  subsets: ["latin"],
  weight: ["700", "400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"

};


export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    // TODO подумай о языке
    <html lang="en">
    <body className={`${fontRegular.variable} ${fontBold.variable}`}>
    <AppRouterCacheProvider options={{ key: "css" }}>
      <ThemeProvider theme={theme}>
        <Box className={"layout"}>
          <GlobalStyles styles={globalStyling} />
          <Header />
          <Box className={"layout__content"}>
            {children}
          </Box>
          <Footer />
        </Box>
      </ThemeProvider>
    </AppRouterCacheProvider>
    </body>
    </html>
  );
}

