import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
            типо header
            <Link href={"./"}>
                Home
            </Link>
            <Link href={"./tracks"}>
                Tracks
            </Link>
            <Link href={"./poems"}>
                Poems
            </Link>
            <Link href={"./website"}>
                Website
            </Link>
            <Link href={"./404"}>
                404
            </Link>
        </div>
        {children}
        </body>
        </html>
    );
}
