import type { Metadata } from "next";
import { Arsenal, Hedvig_Letters_Serif } from "next/font/google";
// import "./globals.scss";
import "./page.scss";
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/Theme/theme";


const fontRegular = Hedvig_Letters_Serif({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400"]
});
const fontBold = Arsenal({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"

};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // TODO подумай о языке
    <html lang="en">
    {/*<head>*/}
    {/*  <meta name="viewport" content="initial-scale=1, width=device-width" />*/}
    {/*</head>*/}

    <body className={`${fontRegular.variable} ${fontBold.variable}`}>
    <AppRouterCacheProvider options={{ key: "css" }}>
      <ThemeProvider theme={theme}>
        <div className={"layout"}>
          <Header />
          <div className={"layout__content"}>
            {children}
          </div>
          <Footer />
        </div>
      </ThemeProvider>
    </AppRouterCacheProvider>
    </body>
    </html>
  );
}
